version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "04:36"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "rubocop-lts"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
