name: Ancient Compat (EOL, Ruby 2.5) Matrix

on:
  push:
    branches:
      - 'main'
    tags:
      - '!*' # Do not execute on tags
  pull_request:
    branches:
      - '*'
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Specs - Ruby ${{ matrix.ruby }} ${{ matrix.appraisal }}${{ matrix.name_extra || '' }}
    if: "!contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-22.04
    continue-on-error: ${{ matrix.experimental || endsWith(matrix.ruby, 'head') }}
    env: # $BUNDLE_GEMFILE must be set at job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}.gemfile
    strategy:
      fail-fast: false
      matrix:
        include:
          # Ruby 2.3
          - ruby: "2.3"
            appraisal: "ruby-2-3"
            exec_cmd: "rake rspec"
            gemfile: "Appraisal.root"
            rubygems: "3.3.27"
            bundler: "2.3.27"

          # Ruby 2.4
          - ruby: "2.4"
            appraisal: "ruby-2-4"
            exec_cmd: "rake rspec"
            gemfile: "Appraisal.root"
            rubygems: "3.3.27"
            bundler: "2.3.27"

          # Ruby 2.5
          - ruby: "2.5"
            appraisal: "ruby-2-5"
            exec_cmd: "rake rspec"
            gemfile: "Appraisal.root"
            rubygems: "3.3.27"
            bundler: "2.3.27"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby & RubyGems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: ${{ matrix.rubygems }}
          bundler: ${{ matrix.bundler }}
          bundler-cache: false

      # Raw `bundle` will use the BUNDLE_GEMFILE set to matrix.gemfile (i.e. Appraisal.root)
      # We need to do this first to get appraisal installed.
      # NOTE: This does not use the main Gemfile at all.
      - name: Bundle install for Appraisal ${{ matrix.appraisal }}
        run: bundle
      - name: Install Appraisal ${{ matrix.appraisal }} dependencies
        run: bundle exec appraisal ${{ matrix.appraisal }} bundle
      - name: Run ${{ matrix.appraisal }} tests via ${{ matrix.exec_cmd }}
        run: bundle exec appraisal ${{ matrix.appraisal }} bundle exec ${{ matrix.exec_cmd }}
